export { DocumentCrypto } from './crypto.js'
export { getStorageAdapter } from './storage-adapter.js'
export type { Platform } from './storage-adapter.js'
export { RepoManager, KeyNotFoundError } from './repo-manager.js'
export type { StorageAdapter, StorageAdapterInterface, Chunk } from '@automerge/automerge-repo'
